---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: testingsomething
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/main-base-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - chromium


  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system

        install:
          - org.signal.Signal
      - scope: user 

  - type: signing
